from os.path import join

# Rutas
RUTA_AMBIENTES = join("datos", "ambientes.csv")
RUTA_ARENAS = join("datos", "arenas.csv")
RUTA_OBJETOS = join("datos", "objetos.csv")
RUTA_TRIBUTOS = join("datos", "tributos.csv")

# Parametros
ENERGIA_ACCION_HEROICA = 8
POPULARIDAD_ACCION_HEROICA = 4
ENERGIA_ATACAR = 6
POPULARIDAD_ATACAR = 3
POPULARIDAD_PEDIR = 2
ENERGIA_BOLITA = 2
AUMENTAR_ENERGIA = 5
PONDERADOR_AUMENTAR_FUERZA = 2
AUMENTAR_AGILIDAD = 2
AUMENTAR_INGENIO = 1
PROBABILIDAD_EVENTO = 0.4  # máximo dos decimales
VELOCIDAD_VIENTOS_PLAYA = 90
HUMEDAD_PLAYA = 70
NUBOSIDAD_MONTAÑA = 110
PRECIPITACIONES_MONTAÑA = 130
PRECIPITACIONES_BOSQUE = 120
VELOCIDAD_VIENTOS_BOSQUE = 70
